WEB/Controllers/Implementation/BankController.cs
using BLL.Interfaces;
using Microsoft.Extensions.Logging;
using sharps_ent.Entity;
using System.Linq;

namespace sharps_ent.Controllers
{
    public sealed class BankController : GenericController
    {

        private readonly IBankService bankService;
        public BankController(ILogger<GenericController> logger, IBankService bankService) : base(logger)
        {
            this.bankService = bankService;
        }

        public override string[] Labels => new string[]{ "NameOfBank", "Information" };

        protected override void AddObject()
        {
            var @object = new Bank
            {
                NameOfBank = HttpContext.Request.Form["1"],
                Information = HttpContext.Request.Form["2"],
            };
            bankService.CreateBank(@object);
        }

        protected override string[][] GetObjects(bool id = false)
        {
            var objects = bankService.GetBanks();
            if (HttpContext.Request.Method == "POST")
            {
                if (id)
                {
                    objects = objects.Where(x => x.BankId.ToString() == HttpContext.Request.Form["id"]);
                }
                else
                {
                    if (HttpContext.Request.Form.ContainsKey("0") && HttpContext.Request.Form["0"] != "")
                    {
                        objects = objects.Where(x => x.BankId.ToString() == HttpContext.Request.Form["0"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("1") && HttpContext.Request.Form["1"] != "")
                    {
                        objects = objects.Where(x => x.NameOfBank == HttpContext.Request.Form["1"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("2") && HttpContext.Request.Form["2"] != "")
                    {
                        objects = objects.Where(x => x.Information == HttpContext.Request.Form["2"]);
                    }
                }
            }
            var cells = objects.Select(x => new string[] {
                x.BankId.ToString(), x.NameOfBank, x.Information
            }).ToArray();
            return cells;
        }

        protected override void UpdateObject()
        {
            var @object = bankService.GetBankById(int.Parse(HttpContext.Request.Form["0"]));
            @object.NameOfBank = HttpContext.Request.Form["1"];
            @object.Information = HttpContext.Request.Form["2"];
            bankService.UpdateBank(@object);
        }

        protected override void RemoveObject()
        {
            bankService.DeleteBank(bankService.GetBankById(int.Parse(HttpContext.Request.Form["id"])));
        }
    }
}

WEB/Controllers/Implementation/CityController.cs
using BLL.Interfaces;
using Microsoft.Extensions.Logging;
using sharps_ent.Entity;
using System.Collections.Generic;
using System.Linq;

namespace sharps_ent.Controllers
{
    public sealed class CityController : GenericController
    {

        private readonly ICityService cityService;
        private readonly ICountryService countryService;
        public CityController(ILogger<GenericController> logger, ICityService cityService, ICountryService countryService) : base(logger)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        public override string[] Labels => new string[]{ "NameOfCity", "Country" };

        protected override void AddObject()
        {
            var @object = new City
            {
                NameOfCity = HttpContext.Request.Form["1"],
                CountryId = int.Parse(HttpContext.Request.Form["2"]),
            };
            cityService.CreateCity(@object);
        }

        protected override string[][] GetObjects(bool id = false)
        {
            var objects = cityService.GetCities();
            if (HttpContext.Request.Method == "POST")
            {
                if (id)
                {
                    objects = objects.Where(x => x.CityId.ToString() == HttpContext.Request.Form["id"]);
                }
                else
                {
                    if (HttpContext.Request.Form.ContainsKey("0") && HttpContext.Request.Form["0"] != "")
                    {
                        objects = objects.Where(x => x.CityId.ToString() == HttpContext.Request.Form["0"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("1") && HttpContext.Request.Form["1"] != "")
                    {
                        objects = objects.Where(x => x.NameOfCity.ToString() == HttpContext.Request.Form["1"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("2") && HttpContext.Request.Form["2"] != "")
                    {
                        objects = objects.Where(x => countryService.GetCountryById(x.CountryId).NameOfCountry == HttpContext.Request.Form["2"]);
                    }
                }
            }
            var cells = objects.Select(x => new string[] {
                x.CityId.ToString(), x.NameOfCity.ToString(), x.CountryId.ToString()
            }).ToArray();
            return cells;
        }

        protected override void UpdateObject()
        {
            var @object = cityService.GetCityById(int.Parse(HttpContext.Request.Form["0"]));
            @object.NameOfCity = HttpContext.Request.Form["1"];
            @object.CountryId = int.Parse(HttpContext.Request.Form["2"]);
            cityService.UpdateCity(@object);
        }

        protected override void RemoveObject()
        {
            cityService.DeleteCity(cityService.GetCityById(int.Parse(HttpContext.Request.Form["id"])));
        }
        protected override Dictionary<int, string> GetAttributes() => new Dictionary<int, string>() { { 2, "Country" } };

        protected override object GetNames() => new Dictionary<int, string[]> {
            { 2, cityService.GetCities().Where(x => GetObjects().Select(y => y[0]).Contains(x.CityId.ToString())).Select(x => countryService.GetCountryById(x.CountryId)?.NameOfCountry).ToArray() }
        };
    }
}

WEB/Controllers/Implementation/LogController.cs
using BLL.Interfaces;
using Microsoft.Extensions.Logging;
using sharps_ent.Entity;
using System.Collections.Generic;
using System.Linq;

namespace sharps_ent.Controllers
{
    public sealed class LogController : GenericController
    {
        private readonly ILogOfOperationsService logService;
        private readonly IEmployeeService employeeService;
        private readonly IDepositorService depositorService;
        private readonly ITypeOperationService typeOperationService;

        public LogController(ILogger<GenericController> logger, ILogOfOperationsService logService, IEmployeeService employeeService, IDepositorService depositorService, ITypeOperationService typeOperationService) : base(logger)
        {
            this.logService = logService;
            this.employeeService = employeeService;
            this.depositorService = depositorService;
            this.typeOperationService = typeOperationService;
        }

        public override string[] Labels => new string[] { "Employee", "Depositor", "Type", "Quantity" };

        protected override void AddObject()
        {
            var @object = new LogOfOperations
            {
                EmployeeId = int.Parse(HttpContext.Request.Form["1"]),
                DepositorId = int.Parse(HttpContext.Request.Form["2"]),
                TypeId = int.Parse(HttpContext.Request.Form["3"]),
                Quantity = int.Parse(HttpContext.Request.Form["4"])
            };
            logService.CreateLogOfOperations(@object);
        }

        protected override string[][] GetObjects(bool id = false)
        {
            var objects = logService.GetLogOfOperations();
            if (HttpContext.Request.Method == "POST")
            {
                if (id)
                {
                    objects = objects.Where(x => x.OperationId.ToString() == HttpContext.Request.Form["id"]);
                }
                else
                {
                    if (HttpContext.Request.Form.ContainsKey("0") && HttpContext.Request.Form["0"] != "")
                    {
                        objects = objects.Where(x => x.OperationId.ToString() == HttpContext.Request.Form["0"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("1") && HttpContext.Request.Form["1"] != "")
                    {
                        objects = objects.Where(x => employeeService.GetEmployeeById(x.EmployeeId).NameOfEmployee == HttpContext.Request.Form["1"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("2") && HttpContext.Request.Form["2"] != "")
                    {
                        objects = objects.Where(x => depositorService.GetDepositorById(x.DepositorId).NameOfDepositor == HttpContext.Request.Form["2"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("3") && HttpContext.Request.Form["3"] != "")
                    {
                        objects = objects.Where(x => typeOperationService.GetTypeOperationById(x.TypeId).NameOfType == HttpContext.Request.Form["3"]);
                    }
                    if (HttpContext.Request.Form.ContainsKey("4") && HttpContext.Request.Form["4"] != "")
                    {
                        objects = objects.Where(x => x.Quantity.ToString() == HttpContext.Request.Form["4"]);
                    }
                }
            }
            var cells = objects.Select(x => new string[] {
                x.OperationId.ToString(), x.EmployeeId.ToString(), x.DepositorId.ToString(), x.TypeId.ToString(), x.Quantity.ToString()
            }).ToArray();
            return cells;
        }

        protected override void UpdateObject()
        {
            var @object = logService.GetLogOfOperationsById(int.Parse(HttpContext.Request.Form["0"]));
            @object.EmployeeId = int.Parse(HttpContext.Request.Form["1"]);
            @object.DepositorId = int.Parse(HttpContext.Request.Form["2"]);
            @object.TypeId = int.Parse(HttpContext.Request.Form["3"]);
            @object.Quantity = int.Parse(HttpContext.Request.Form["4"]);
            logService.UpdateLogOfOperations(@object);
        }

        protected override void RemoveObject()
        {
            logService.DeleteLogOfOperations(logService.GetLogOfOperationsById(int.Parse(HttpContext.Request.Form["id"])));
        }
        protected override Dictionary<int, string> GetAttributes() => new Dictionary<int, string>() { { 1, "Employee" }, { 2, "Depositor" }, { 3, "Type" } };

        protected override List<string> GetStat() => new List<string>{ $"Количество денег: {((IEnumerable<LogOfOperations>)GetStatObj()).Select(x => x.Quantity).Sum()}", $"Количество вкладчиков: {((IEnumerable<LogOfOperations>)GetStatObj()).Select(x => x.DepositorId).Distinct().Count()}", $"Количество работников: {((IEnumerable<LogOfOperations>)GetStatObj()).Select(x => x.EmployeeId).Distinct().Count()}" };

        protected override object GetStatObj()
        {
            var objects = logService.GetLogOfOperations();
            if (HttpContext.Request.Method == "POST")
            {
                if (HttpContext.Request.Form.ContainsKey("0") && HttpContext.Request.Form["0"] != "")
                {
                    objects = objects.Where(x => x.OperationId.ToString() == HttpContext.Request.Form["0"]);
                }
                if (HttpContext.Request.Form.ContainsKey("1") && HttpContext.Request.Form["1"] != "")
                {
                    objects = objects.Where(x => employeeService.GetEmployeeById(x.EmployeeId).NameOfEmployee == HttpContext.Request.Form["1"]);
                }
                if (HttpContext.Request.Form.ContainsKey("2") && HttpContext.Request.Form["2"] != "")
                {
                    objects = objects.Where(x => depositorService.GetDepositorById(x.DepositorId).NameOfDepositor == HttpContext.Request.Form["2"]);
                }
                if (HttpContext.Request.Form.ContainsKey("3") && HttpContext.Request.Form["3"] != "")
                {
                    objects = objects.Where(x => typeOperationService.GetTypeOperationById(x.TypeId).NameOfType == HttpContext.Request.Form["3"]);
                }
                if (HttpContext.Request.Form.ContainsKey("4") && HttpContext.Request.Form["4"] != "")
                {
                    objects = objects.Where(x => x.Quantity.ToString() == HttpContext.Request.Form["4"]);
                }
            }
            return objects;
        }

        protected override object GetNames() => new Dictionary<int, string[]> {
            { 1, logService.GetLogOfOperations().Where(x => GetObjects().Select(y => y[0]).Contains(x.OperationId.ToString())).Select(x => employeeService.GetEmployeeById(x.EmployeeId).NameOfEmployee).ToArray() } ,
            { 2, logService.GetLogOfOperations().Where(x => GetObjects().Select(y => y[0]).Contains(x.OperationId.ToString())).Select(x => depositorService.GetDepositorById(x.DepositorId).NameOfDepositor).ToArray() } ,
            { 3, logService.GetLogOfOperations().Where(x => GetObjects().Select(y => y[0]).Contains(x.OperationId.ToString())).Select(x => typeOperationService.GetTypeOperationById(x.TypeId).NameOfType).ToArray() } ,
        };
    }
}

WEB/Controllers/StatisticsController.cs
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Text;

namespace sharps_ent.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly IBankService serviceBank;
        private readonly IBranchService serviceBranch;
        private readonly IDepositorService serviceDepositor;
        private readonly IEmployeeService serviceEmployee;
        private readonly IStreetService serviceStreet;
        private readonly ICityService serviceCity;
        private readonly ICountryService serviceCountry;
        private readonly ILogOfOperationsService serviceLog;
        private readonly IDepositService serviceDeposit;

        public StatisticsController(ILogOfOperationsService serviceLog, IEmployeeService serviceEmployee, IBranchService serviceBranch, IDepositorService serviceDepositor = null, IBankService serviceBank = null, IStreetService serviceStreet = null, ICityService serviceCity = null, ICountryService serviceCountry = null, IDepositService serviceDeposit = null)
        {
            this.serviceLog = serviceLog;
            this.serviceEmployee = serviceEmployee;
            this.serviceBranch = serviceBranch;
            this.serviceDepositor = serviceDepositor;
            this.serviceBank = serviceBank;
            this.serviceStreet = serviceStreet;
            this.serviceCity = serviceCity;
            this.serviceCountry = serviceCountry;
            this.serviceDeposit = serviceDeposit;
        }

        private string[][] GetStat()
        {
            return new string[][] {
                        new string[] { "Количество денег в банках", serviceLog.GetLogOfOperations().Select(x => x.Quantity).Sum().ToString() },
                        new string[] { "Количество банков", serviceBank.GetBanks().Count().ToString() },
                        new string[] { "Количество банковских отделений", serviceBranch.GetBranches().Count().ToString() },
                        new string[] { "Количество клиентов банков", serviceDepositor.GetDepositors().Count().ToString() },
                        new string[] { "Количество рабочих в банках", serviceEmployee.GetEmployees().Count().ToString() },
                        new string[] { "Количество улиц", serviceStreet.GetStreets().Count().ToString() },
                        new string[] { "Количество городов", serviceCity.GetCities().Count().ToString() },
                        new string[] { "Количество стран", serviceCountry.GetCountries().Count().ToString() },
                        new string[] { "Количество операций", serviceLog.GetLogOfOperations().Count().ToString() },
                        new string[] { "Количество вкладов", serviceDeposit.GetDeposits().Count().ToString() },
                    };
        }

        public ActionResult Show()
        {
            return View("~/Views/Statistics.cshtml",
                new object[] { new string[] { "Метрика", "Значение" },
                    GetStat()
                });
        }

        public ActionResult Download()
        {
            var memStream = new MemoryStream();
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            var streamWriter = new StreamWriter(memStream, Encoding.GetEncoding("windows-1251"));
            foreach (var fe in GetStat())
            {
                streamWriter.WriteLine($"{fe[0]};{fe[1]}");
            }
            streamWriter.Flush();
            memStream.Seek(0, SeekOrigin.Begin);
            string file_type = "application/csv";
            string file_name = "Stat.csv";
            return File(memStream, file_type, file_name);
        }
    }
}

WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sharps_ent</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href=https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css rel=stylesheet>
    <link href=https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/dataTables.bootstrap4.min.css rel=stylesheet>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sharps_ent</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="GetResponceAction2">Bank</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="GetResponceAction2">Branch</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Street" asp-action="GetResponceAction2">Street</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="GetResponceAction2">City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="GetResponceAction2">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Status" asp-action="GetResponceAction2">Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Type" asp-action="GetResponceAction2">Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depositor" asp-action="GetResponceAction2">Depositor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="GetResponceAction2">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Log" asp-action="GetResponceAction2">Log</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deposit" asp-action="GetResponceAction2">Deposit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Show">Statistics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>